name_mapping = {
    "orchid green Mumbai": "ORCHIDS INTERNATIONAL MUMBAI",
    "kapoor plastic new": "KAPOOR PLASTICS SRE",
    "a k trading": "A.K. TRADING CO. SRE",
    "Sanjeev Distributors CB": "SANJEEV DISTRIBUTORS JWP",
    "Shree Balaji Enterprises Dehradun": "SHREE BALAJI ENTERPRISES D.DUN",
    "Shri Laxmi Bhawani Agencies": "SHRI LAXMI BHAWANI AGENCIES RKE",
    "TARANG AGENCIES JWP": "TARANG AGENCIES JWP",
    "Shree Jain Radios Saharanpur": "SHREE JAIN RADIOS SRE",
    "Kaushal enterprises rke": "KAUSHAL ENTERPRISES RKE",
    "malik trading company ok": "MALIK TRADING CO. DELHI",
    "Shri Krishna Engineering Works DLH": "SHRI KRISHNA ENGG. WORKS DELHI",
    "Shri Krishna Engineering works hdfc": "SHRI KRISHNA ENGG. WORKS DELHI",
    "Kumar and  sons": "KUMAR & SONS SRE",
    "NOOTAN WARE HOUSE Moradabad": "NOOTAN WARE HOUSE MRD",
    "Ena Enterprises Jwalapur": "ENA ENTERPRISES JWP",
    "Shri Sai Agencies Rke": "SHRI SAI AGENCIES RKE",
    "royal traders hrw": "ROYAL TRADERS HRD",
    "royal enterprises": "ROYAL ENTERPRISES RKE",
    "archive international jwp": "ACHIEVE INTERNATIONAL JWP",
    "shri adinath traders ok": "SHREE ADINATH TRADERS BAJAJ RKE",
    "t p traders dl ok": "TP TRADERS DELHI",
    "jain brother dlh napkin": "JAIN BROTHERS DELHI",
    "Osho distributor RK": "OSHO DISTRIBUTORS RKE",
    "shri Krishna inalai jwp": "SHRI KRISHNA ENTERPRISES HRD",
    "Manchanda Trading Co Rishikesh": "MANCHANDA TRADING CORPORATION RISHIKESH",
    "Atc rsk": "AJAY TRADECORPORATION P LTD. RISHIKESH",
    "KB Sales Associates jwl": "KB SLES AND ASSOCIATES JWP",
    "dehradun marketing networ": "DEHRADUN MARKETING NETWORK D.DUN",
    "Arora Brother Roorkee": "ARORA BROTHERS RKE",
    "H S TRADING CO SRE": "H.S. TRADING COMPANY SRE",
    "Gandhi Plastic Rishikesh": "GANDHI PLASTIC RISHIKESH",
    "garg traders roorkee": "GARG TRADERS RKE",
    "Kumar Distributor Jwalapur": "KUMAR DISTRIBUTORS JWP",
    "Ganga Plastics Center": "GANGA PLASTIC CENTER HRD",
    "dhruve enterprises jwp": "DHRUV TRADING CO. HRD",
    "KB Small Trade Solutions": "K.B. TRADE SOLUTIONS HRD",
    "om agencies rke": "OM AGENCIES RKE",
    "Bharat Traders Jagadhri": "BHARAT TRADERS JAG",
    "p b khanna and co ok": "P.B. KHANNA & COMPANY DELHI",
    "Rishabh ent jwp ok" : "RISHABH ENTERPRISES JWP",
    "ANIL BROTHERS":"ANIL BROTHRES AGRA",
    "aradhana trading ddn":"ARADHNA TRADING CO. D.DUN",
    "Delhi Traders":"DELHI TRADERS DELHI",
    "Chawla Brothers Old Shop Jagadri":"CHAWLA KITCHEN WARE JAG",
    # "Online Marketing Roorkee":,
    "Manya Enterprises Delhi":"MANYA ENTERPRISES DELHI",
    "Chawla Kitchenware Jagadhri":"CHAWLA KITCHEN WARE JAG",
    "Gulshan dlh": "V.K. MEHRA  & SONS DELHI",
    "maharani mixer ishan": "ISHAAN HOME APPLIANCES DELHI",
    # "spacevogs furniture pvt l":,
    "asha enterprise jdt":"ASHA ENTERPRISES JAG",
    "K K Narang Trading Co Roorkee":"K.K. NARANG TRADING CO. RKE",
    "OK Industries Delh": "O.K. INDUSTRIES DELHI",
    "Bhawani metal industries":"BHAWANI METAL INDUSTRIES MBD",
    "mehra dons dlh":"V.K. MEHRA  & SONS DELHI", #doubt
    # "MANCHANDA TRADING CO TAG":"MANCHANDA TRADING CORPORATION RISHIKESH",
    "dhasmesh trades":"DASHMESH TRADERS RKE",
    "Online Marketing Roorkee":"ON LINE MARKETING RKE",
    "Mulakh Raj  Sons Delhi":"R.S.MULKH RAJ & SONS DELHI",
    "natraj agency":"NATRAJ AGENCY SRE",
    "spacevogs furniture pvt l":"SPACE VEGUES FURNITURES P LTD  RKE",
    "Ritu KH hdfcc":"PERSONAL",
    "manoj kumar":"PERSONAL",
    "Radhika Enterprises Delhi":"RADHIKA ENTERPRISES DELHI",
    "sachdeva store DDN":"SACHDEVA STORE D.DUN",
    "shri krisna trading co rk":"SRI KRISHNA TRADING CO. TANSHIPUR",
    "vikas home decor":"VIKAS HOME DECOR RKE",
    "Ajay traders shamli":"AJAY TRADERS SHAMLI",
    "KISHORI LAL BALWANT RAI Jagadhri":"KISHORI LAL BALWANT RAI JAG",
    "SACHDEVA AGENCY DDN":"SACHDEVA AGENCIES D DUN",
    "kapoor Chand pawan Kumar":"KAPUR CHAND PAWAN KUMAR CHD",
    "SumerChand Ambika Prasad":"SUMER CHAND AMBIKA PRASHAD JAG",
    "m k industry":"M.K. INDUSTRIES SONIPAT",
    
    # new
    "BHAWANI SHANKAR AND SONS Delhi":"BHAWANI SHANKAR & SONS DELHI",
    "Hamnami Store":"HAMNANI STORE DELHI",
    "shree plastic sre":"SHREE PLASTIC SRE",
    
    "Shyam Brassware Shamli":"SHYAM BRASS WARE SHAMLI",
    "shri krisna enterpriseJWP":"SHRI KRISHNA ENTERPRISES HRD",
    "shri krishna traders dlh":"SHRI KRISHNA TRADERS DELHI",
    "shree ji enterprise jwp":"SHREE JI ENTERPRISES JWP",
    "Cee Aar Products Jagadhri":"CEE AAR PRODUCTS JAGD.",
    "a k trading co sre":"A.K. TRADING CO. SRE",
    "ARORA PLASTIC":"ARORA PLASTICS DELHI",
    
    "Ajay Machinery and Mill Store SRE":"AJAY MACHINERY & MILL STORE SRE",
    "Vardhman Enterprises":"VARDHMAN ENTERPRISES D.DUN",
    "Chaman Lal Rajinder Kumar":"CHAMAN LA; RAJENDER KUMAR JAG",
    "chaman lal Rajender Kumar":"CHAMAN LA; RAJENDER KUMAR JAG",
    "Rangoli khandelwal" :"PERSONAL",
    "dev bhoomi enterprise ddn":"DEV BHOOMI ENTERPRISE U.K",
    "vijay machinery store":"VIJAY MACHINARY STORE SRE",
    "om bartan bhandar new": "OM AGENCIES RKE",
    

    
    # no invoice till no:
    "rama agency rke ok" : "RAMA AGENCY RKE",
    "exident enterprises": "EXIDENT ENTERPRISES",
    "Ram Narain Ashok Kumar Jagadhri":"RAM NARAIN ASHOK KUMAR JAG",
    
    # feb new
    "paras enterprise ddn":"PARAS ENTERPRISES D.DUN",
    "Manjit Traders Jagadhri":"MANJEET TRADERS  JAG",
    "nootan wear house mb":"NOOTAN WARE HOUSE MRD",
    "bhagwati crocery sre":"BHAGWATI CROCKERY STORE SRE"
}

account_mapping={
    "00000032303114485":"SHIVAM TRADERS SRE",
    "32303114485":"SHIVAM TRADERS SRE",
    "00000038573343921":"PABREJA BARTAN BHANDAR  MANGLORE",
    "38573343921":"PABREJA BARTAN BHANDAR  MANGLORE",
    # "00000039675596335":"rsm enterprises mohali",
    # "00000061339160386":"oms enterprises",
    # "00000035178834069":"m a enterprises ddn",
    # "00000034903220554":"goyel super Store",
    # "00000061327202991":"Appliances World",
    "00000036560517489":"KANISHK PLASTIC & CO. SRE",
    "36560517489":"KANISHK PLASTIC & CO. SRE",
    "30385154595":"DESHRI DISTRIBUTORS 24-25 SRE",
    "00000030385154595":"DESHRI DISTRIBUTORS 24-25 SRE",
    "35275862303": "ARIHANT PLASTICS D.DUN",
    "00000035275862303": "ARIHANT PLASTICS D.DUN",
    "00000065249946451": "SUGAN CHAND SOHAN LAL SHAMLI",
    "65249946451": "SUGAN CHAND SOHAN LAL SHAMLI",
    "41449085865":"LAKSHAY BALIYAN ENTERPRISES HRD"
}